Repository CodeJaws/Jawstify, pull requests merged in 2023-12, with the labels that each got.

#7 [#5] GitHub CI 설정 / PR 템플릿 추가
  .eslintrc.json
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/workflows/ci.yml
  pages/_app.tsx
Labels: 🟢 Feat

#11 [#10] styled-components 패키지 설치
  next.config.js
  package-lock.json
  package.json
Labels: ⚙️ Chore, 🟢 Feat

#15 [#14] Feat: 페이지 구조 설정
  apis/.gitkeep
  components/.gitkeep
  constants/.gitkeep
  hooks/.gitkeep
  pages/[boardid]/edit.tsx
  pages/[boardid]/index.tsx
  pages/boards/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/myboard/index.tsx
  pages/mydashboard/index.tsx
  pages/notfound/index.tsx
  pages/signup/index.tsx
Labels: 🟢 Feat

#16 [#9] global style 설정 및 color 변수 지정
  pages/_app.tsx
  pages/_document.tsx
  styles/.gitkeep
  styles/GlobalStyles.tsx
  styles/mediaQuery.ts
  styles/palettes.ts
  styles/reset.ts
Labels: 🎨 Design, 🟢 Feat

#19 [#18] fontStyle 구현
  styles/fontStyle.tsx
Labels: 🟢 Feat

#22 [#6] 대시보드 헤더
  components/Dashboard/Button.tsx
  components/Dashboard/Members.tsx
  components/Dashboard/Navbar.tsx
  components/Dashboard/Profile.tsx
  hooks/useDeviceType.ts
  public/assets/icons/crown.svg
  public/assets/icons/invite.svg
  public/assets/icons/setting.svg
  styles/mediaQuery.ts
  styles/palettes.ts
  styles/reset.ts
  utils/createSlicedMembers.ts
Labels: 📂 Create, 🟢 Feat

#13 [#8] Chip 컴포넌트
  .prettierrc
  components/Chip/AddChip.tsx
  components/Chip/ColorChip.tsx
  components/Chip/ContentChip.tsx
  components/Chip/CountChip.tsx
  components/Chip/StatusChip.tsx
  constants/Chip.ts
  public/assets/icons/Add.svg
  public/assets/icons/BlueEllipse.svg
  public/assets/icons/Check.svg
  public/assets/icons/ChipEllipse.svg
  public/assets/icons/GreenEllipse.svg
  public/assets/icons/OrangeEllipse.svg
  public/assets/icons/PinkEllipse.svg
  public/assets/icons/PurpleEllipse.svg
  styles/palettes.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#29 [#28] Refactor: 컬러 팔레트 네이밍 변경
  components/Chip/AddChip.tsx
  components/Chip/ColorChip.tsx
  components/Chip/ContentChip.tsx
  components/Chip/CountChip.tsx
  components/Chip/StatusChip.tsx
  components/Dashboard/Button.tsx
  components/Dashboard/Members.tsx
  components/Dashboard/Navbar.tsx
  components/Dashboard/Profile.tsx
  styles/fontStyle.tsx
  styles/palettes.ts
Labels: ♻️ Refactor, 🎨 Design

#31 [#24] Sidebar 컴포넌트
  components/Sidebar/DashboardGroup.tsx
  components/Sidebar/Sidebar.tsx
  hooks/useDeviceType.ts
  pages/[boardid]/edit.tsx
  pages/[boardid]/index.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/boards/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/myboard/index.tsx
  pages/mydashboard/index.tsx
  pages/notfound/index.tsx
  pages/signup/index.tsx
  pages/test/index.tsx
  public/assets/icons/LogoSidebar.svg
  public/assets/icons/LogoSidebarTitle.svg
  styles/GlobalStyles.tsx
  styles/mediaQuery.ts
  styles/reset.ts
  utils/createSlicedMembers.ts
Labels: 🎨 Design, 🟢 Feat

#30 [#4] Button 컴포넌트
  components/common/Button/AddButton.tsx
  components/common/Button/Button.tsx
  components/common/Button/ColumnAddButton.tsx
  components/common/Button/DashBoardAddButton.tsx
  components/common/Button/DashBoardButton.tsx
  components/common/Button/DeleteButton.tsx
  components/common/Button/LoginButton.tsx
  components/common/Button/PaginationButton.tsx
  components/common/Button/TwinButton.tsx
  public/assets/icons/crown.svg
  public/assets/icons/greenCircle.svg
  public/assets/icons/leftPage.svg
  public/assets/icons/lightLeftPage.svg
  public/assets/icons/lightRightPage.svg
  public/assets/icons/plus.svg
  public/assets/icons/rightPage.svg
  styles/reset.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#27 [#25] ModalDropdown 컴포넌트
  components/Chip/StatusChip.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/ModalDropDown/ModalDropDown.tsx
  public/assets/icons/ArrowDropdown.svg
  public/assets/icons/GrayCheck.svg
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#40 [#39] Button 컴포넌트 수정
  components/common/Button/Button.tsx
  components/common/Button/LoginButton.tsx
  components/common/Button/TwinButton.tsx
Labels: 🛠️ Fix

#35 [#33] 이미지 추가 버튼 컴포넌트
  components/AddImageButton/AddImageButton.tsx
  public/assets/icons/EditImage.svg
  styles/palettes.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#37 [#12] Input 컴포넌트
  components/Chip/ContentChip.tsx
  components/Input/FormInput.tsx
  components/Input/Input.style.ts
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Input/ModalInputContainer/DateInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  constants/Input.ts
  package-lock.json
  package.json
  pages/test/index.tsx
  public/assets/icons/calendar.svg
  public/assets/icons/eyeoff.svg
  public/assets/icons/eyeon.svg
  utils/validation.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#44 [#42] 버튼들에 onClick 기본 설정 추가
  components/common/Button/AddButton.tsx
  components/common/Button/Button.tsx
  components/common/Button/ColumnAddButton.tsx
  components/common/Button/DashBoardAddButton.tsx
  components/common/Button/DashBoardButton.tsx
  components/common/Button/DeleteButton.tsx
  components/common/Button/TwinButton.tsx
  types/button.ts
Labels: 🛠️ Fix

#48 [#47] 버튼 styled 입힐 수 있도록 기능 추가 및 기타 사항 수정
  components/Input/ModalInputContainer/BasicInput.tsx
  components/common/Button/Button.tsx
  components/common/Button/TwinButton.tsx
Labels: 🛠️ Fix

#55 [#47] BasicInput 주석 삭제
  components/Input/ModalInputContainer/BasicInput.tsx
Labels: 🎨 Style

#54 [#53] useDeviceType 함수 수정
  hooks/useDeviceType.ts
  pages/_document.tsx
Labels: 🛠️ Fix

#49 [#26] Table 컴포넌트
  components/Table/InviteButton.tsx
  components/Table/TablePagination.tsx
  components/common/Button/PaginationButton.tsx
  hooks/usePagination.ts
  pages/test/index.tsx
  public/assets/icons/AddBoxWhite.svg
Labels: ♻️ Refactor, 📂 Create, 🎨 Design, 🟢 Feat

#45 [#17] 메인 랜딩 페이지 구현
  components/Landing/Card.tsx
  components/Landing/Footer.tsx
  components/Landing/Hero.tsx
  components/Landing/Nav.tsx
  components/Landing/Point.tsx
  components/common/Button/LoginButton.tsx
  pages/index.tsx
  public/assets/.gitkeep
  public/assets/fonts/Montserrat/Montserrat-Bold.ttf
  public/assets/icons/emailIcon.svg
  public/assets/icons/facebookIcon.svg
  public/assets/icons/instagramIcon.svg
  public/assets/icons/logoImage.svg
  public/assets/icons/logoText.svg
  public/assets/images/landing1.png
  public/assets/images/landing2.png
  public/assets/images/landing3.png
  public/assets/images/landing4.png
  public/assets/images/landing5.png
  public/assets/images/landing6.png
  styles/palettes.ts
  styles/reset.ts
Labels: 🟢 Feat

#50 [#36] Modal Card 컴포넌트
  components/Chip/ContentChip.tsx
  components/Input/ModalInputContainer/BasicInput.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/Menu.tsx
  components/ModalCard/ModalButton.tsx
  components/ModalCard/ModalCard.tsx
  pages/modalcard/index.tsx
  public/assets/icons/Close.svg
  public/assets/icons/MenuButton.svg
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#59 [#34] 테이블 대시보드 컴포넌트 구현
  components/Table/InviteDashBoard.tsx
  components/common/Button/TwinButton.tsx
  hooks/useDeviceType.ts
  package-lock.json
  package.json
  pages/_document.tsx
  public/assets/icons/Search.svg
  utils/createSlicedMembers.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#62 [#61] Fix: 대시보드 헤더 위치 오류 및 CSS 수정
  components/Dashboard/DashboardNavbar.tsx
Labels: 🎨 Design, 🛠️ Fix

#64 [#63] Fix: Sidebar CSS 오류 수정
  components/Sidebar/DashboardGroup.tsx
  components/Sidebar/Sidebar.tsx
Labels: 🎨 Design, 🛠️ Fix

#56 [#51] Modal Input Dropdwon 컴포넌트
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/ModalDropDown/ModalDropDown.tsx
  constants/Chip.ts
  types/dropdown.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#66 [#52] API 작성
  apis/api.ts
  apis/axios.ts
  next.config.js
  types/api.ts
  utils/localStorage.ts
Labels: ♻️ Refactor, 📂 Create, 🟢 Feat

#68 [#58] 계정관리 페이지
  components/AddImageButton/AddImageButton.tsx
  components/Dashboard/DashboardNavbar.tsx
  components/Dashboard/Members.tsx
  components/Input/Input.style.ts
  components/MyPage/PasswordManagerBox.tsx
  components/MyPage/ProfileBox.tsx
  components/Sidebar/Sidebar.tsx
  pages/mypage/index.tsx
  public/assets/icons/LeftArrow.svg
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#79 [#78] 대시보드 Navbar CSS 수정
  components/DashboardNavbar/Button.tsx
  components/DashboardNavbar/DashboardNavbar.tsx
  components/DashboardNavbar/Members.tsx
  components/DashboardNavbar/Profile.tsx
  pages/mypage/index.tsx
Labels: 🎨 Design, 🛠️ Fix

#71 [#41] Modal 컴포넌트
  components/Chip/ColorChip.tsx
  components/Chip/ContentChip.tsx
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Input/ModalInputContainer/DateInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  components/Modal/ModalContent/NoTitle.tsx
  components/ModalCard/Comment.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/ModalDropDown/ModalDropDown.tsx
  components/MyPage/PasswordManagerBox.tsx
  components/common/Button/Button.tsx
  components/common/Button/TwinButton.tsx
  package-lock.json
  package.json
  pages/_document.tsx
  types/modal.ts
Labels: ♻️ Refactor, 🎨 Design, 🟢 Feat

#73 [#72] Modal Dropdown 컴포넌트 state 관리
  components/Chip/ColorChip.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  hooks/DropDown/useImgSrc.ts
  hooks/DropDown/useInputData.ts
  hooks/DropDown/useSelectStatus.ts
  package-lock.json
  package.json
Labels: ♻️ Refactor, ⚙️ Chore, 🟢 Feat

#81 [#74] Login, SignUp 페이지
  components/Input/FormInput.tsx
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Input/ModalInputContainer/DateInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Landing/Hero.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  components/Modal/ModalContent/NoTitle.tsx
  components/common/Button/LoginButton.tsx
  constants/ModalInput.ts
  constants/SignValidate.ts
  hooks/useAuth.ts
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/icons/mainPurpleLogo.svg
  types/button.ts
  types/modal.ts
  utils/validation.ts
Labels: ♻️ Refactor, 📂 Create, 🟢 Feat

#91 [#90] BasicModal 버튼 비활성화 기능 구현
  components/Modal/ModalContent/Basic.tsx
  components/common/Button/TwinButton.tsx
Labels: 🟢 Feat

#93 [#92] Feat(404page): 404 페이지 구현
  pages/404/index.tsx
  pages/notfound/index.tsx
  public/assets/images/emoji.webp
Labels: 📂 Create, 🟢 Feat

#86 [#76] 계정관리 페이지 API 연동
  apis/api.ts
  apis/axios.ts
  components/AddImageButton/AddImageButton.tsx
  components/Input/FormInput.tsx
  components/Input/Input.style.ts
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/MyPage/PasswordManagerBox.tsx
  components/MyPage/ProfileBox.tsx
  components/Sidebar/DashboardGroup.tsx
  components/common/Button/Button.tsx
  constants/ErrorMsg.ts
  constants/SignValidate.ts
  next.config.js
  pages/mypage/index.tsx
  types/.gitkeep
  types/api.ts
  utils/.gitkeep
Labels: 🛠️ Fix, ⚙️ Chore, 🟢 Feat

#103 [#102] modal value 기본값 상수화
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  constants/InitialModalValues.ts
Labels: ♻️ Refactor, 📂 Create

#96 [#95] 비밀번호 숨기기 버튼 버그
  components/Input/FormInput.tsx
Labels: 🛠️ Fix

#104 [#102] modal values 상수 이름 대문자로 수정
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  constants/InitialModalValues.ts
Labels: 🛠️ Fix, 🎨 Style

#106 [#105] Fix: Basic Modal 버튼 비활성화 안풀리는 오류 해결
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/common/Button/TwinButton.tsx
Labels: 🛠️ Fix
