Repository CodeJaws/Jawstify, pull requests merged in 2024-01, with the labels that each got.

#114 [#107] 랜딩페이지 다크모드 구현
  components/Landing/Card.tsx
  components/Landing/Footer.tsx
  components/Landing/Hero.tsx
  components/Landing/Nav.tsx
  components/Landing/Point.tsx
  hooks/useTheme.ts
  pages/_document.tsx
  public/assets/icons/moon.svg
  public/assets/icons/sun.svg
  styles/GlobalStyles.tsx
  styles/palettes.ts
  styles/theme.ts
Labels: 🎨 Design, 🟢 Feat

#109 [#60] 나의 대시보드 페이지 구현
  components/Chip/ColorChip.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/MyDashboard/MyDashBoardButtonBox.tsx
  components/Table/InviteDashBoard.tsx
  components/Table/MembersTable.tsx
  components/common/Button/DashBoardButton.tsx
  components/common/Button/TwinButton.tsx
  hooks/usePagination.ts
  package-lock.json
  package.json
  pages/[boardid]/edit.tsx
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  public/assets/images/NoContent.png
  types/api.ts
  types/modal.ts
Labels: 📂 Create, 🎨 Design, 🟢 Feat

#113 [#97] Modal Card API 연동
  apis/api.ts
  components/AddImageButton/AddImageButton.tsx
  components/Chip/ContentChip.tsx
  components/Chip/StatusChip.tsx
  components/Input/Input.style.ts
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Input/ModalInputContainer/DateInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/EditToDo.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/Menu.tsx
  components/ModalCard/ModalButton.tsx
  components/ModalCard/ModalCard.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/ModalDropDown/ModalDropDown.tsx
  components/MyPage/ProfileBox.tsx
  constants/ModalInput.ts
  hooks/DropDown/useGetMember.ts
  hooks/DropDown/useManager.ts
  hooks/DropDown/useModalOpen.ts
  hooks/DropDown/useSelectStatus.ts
  hooks/ModalCard/useCardData.ts
  hooks/ModalCard/useCardId.ts
  hooks/ModalCard/useColumnId.ts
  hooks/ModalCard/useComment.ts
  hooks/ModalCard/useDashBoard.ts
  hooks/ModalCard/useEditTodo.ts
  hooks/useComment.ts
  hooks/useRefresh.ts
  pages/[boardid]/index.tsx
  pages/[dashboardid]/edit.tsx
  pages/[dashboardid]/index.tsx
  pages/modalcard/index.tsx
  types/api.ts
  types/dropdown.ts
  utils/dateTimeFormat.ts
Labels: 🎨 Design, 🟢 Feat

#110 [#85] 사이드바 무한스크롤 구현 + 대시보드 추가 버튼 + 이미지 로고 클릭 구현
  apis/api.ts
  components/Sidebar/Dashboard.tsx
  components/Sidebar/DashboardGroup.tsx
  components/Sidebar/Sidebar.tsx
Labels: 📂 Create, 🎨 Design, 🛠️ Fix, 🟢 Feat

#117 [#116] Modal, ModalContent, DateInput 이용 시 콘솔 에러 해결
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/ManageColumn.tsx
Labels: ♻️ Refactor, 🛠️ Fix

#124 [#122] 할 일 생성 모달 API 연동
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  components/Modal/ModalContent/NoTitle.tsx
  components/ModalDropDown/DropDownMenu.tsx
Labels: 🟢 Feat

#119 [#111] 마이페이지 API 연동
  components/AddImageButton/AddImageButton.tsx
  components/DashboardNavbar/DashboardNavbar.tsx
  components/DashboardNavbar/Profile.tsx
  components/Input/FormInput.tsx
  components/MyPage/PasswordManagerBox.tsx
  components/MyPage/ProfileBox.tsx
  hooks/useUser.ts
  pages/mypage/index.tsx
  types/api.ts
Labels: 🛠️ Fix, 🟢 Feat

#130 [#129] 대시보드 수정페이지 id 접근 오류 해결
  pages/[dashboardid]/edit.tsx
Labels: 🛠️ Fix

#127 [#123] 리다이렉션 구현
  hooks/useRedirectByDashboardId.ts
  hooks/useRedriectByLogin.ts
  pages/[dashboardid]/edit.tsx
  pages/[dashboardid]/index.tsx
  pages/boards/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/myboard/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
Labels: 🟢 Feat

#126 [#80] 대시보드 페이지 구현 (/dashboard/[dashboardid])
  apis/api.ts
  components/Card/Column.tsx
  components/Chip/CountChip.tsx
  components/Columns/Card.tsx
  components/Columns/Column.tsx
  components/Columns/Columns.tsx
  components/Input/ModalInputContainer/DateInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Landing/Hero.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/Basic.tsx
  components/Modal/ModalContent/Create&EditToDo.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/Modal/ModalContent/EditToDo.tsx
  components/Modal/ModalContent/ManageColumn.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/Menu.tsx
  components/ModalCard/ModalButton.tsx
  components/ModalCard/ModalCard.tsx
  components/ModalDropDown/DropDown.tsx
  components/MyDashboard/MyDashBoardButtonBox.tsx
  components/Table/InviteDashBoard.tsx
  constants/InitialModalValues.ts
  hooks/useComment.ts
  pages/[dashboardid]/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/dashboard/cardtest.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  types/api.ts
  utils/dateFormat.ts
Labels: ♻️ Refactor, 📂 Create, 🎨 Design, 🛠️ Fix, 🎨 Style, 🟢 Feat

#133 [#128] 대시보드 Navbar 오류 수정
  components/DashboardNavbar/DashboardNavbar.tsx
  components/DashboardNavbar/Profile.tsx
  pages/dashboard/[dashboardid].tsx
Labels: 🛠️ Fix

#135 [#134] useRedriectByLogin 함수 이름 변경
  hooks/useRedirectByLogin.ts
  pages/[dashboardid]/edit.tsx
  pages/[dashboardid]/index.tsx
  pages/boards/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/myboard/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
Labels: ✏️ Rename

#141 [#140] Fix: string type을 받는 id 값들 number type으로 수정
  components/Columns/Column.tsx
  components/DashboardNavbar/DashboardNavbar.tsx
  components/Edit/DashboardEdit.tsx
  components/Landing/Nav.tsx
  components/Landing/Point.tsx
  components/Table/InviteDetailsTable.tsx
  components/Table/MembersTable.tsx
  pages/[dashboardid]/edit.tsx
  types/api.ts
Labels: 🛠️ Fix

#137 [#136] 수정페이지 오류 해결
  components/Chip/ColorChip.tsx
  components/DashboardNavbar/Profile.tsx
  components/Edit/DashboardEdit.tsx
  components/Edit/MobileColorChip.tsx
  components/Sidebar/Dashboard.tsx
  components/Sidebar/Sidebar.tsx
  components/Table/InviteDetailsTable.tsx
  components/Table/MembersTable.tsx
  constants/InitialModalValues.ts
  pages/[dashboardid]/edit.tsx
Labels: 🛠️ Fix

#139 [#138] 모달 카드 모달로 나오게 하기
  components/Columns/Card.tsx
  components/Columns/Columns.tsx
  components/DashboardNavbar/Members.tsx
  components/DashboardNavbar/Profile.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/ModalButton.tsx
  components/ModalCard/ModalCard.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  constants/ModalInput.ts
  hooks/ModalCard/useCardOpen.ts
  hooks/ModalCard/useDashBoardId.ts
  hooks/ModalCard/useModalCard.ts
  hooks/useComment.ts
  pages/404/index.tsx
  pages/[dashboardid]/index.tsx
  pages/dashboard/[dashboardid].tsx
  pages/mypage/index.tsx
  public/assets/images/emoji.webp
  public/assets/images/jaws.png
Labels: ♻️ Refactor, 📂 Create

#142 [#132] 나의 대시보드 페이지 수정, 사이드바 모든 페이지 작동 수정
  components/Columns/Columns.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  components/Sidebar/Dashboard.tsx
  components/Sidebar/Sidebar.tsx
  components/common/Button/DashBoardButton.tsx
  pages/[dashboardid]/edit.tsx
  pages/dashboard/[dashboardid].tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
Labels: 🛠️ Fix

#144 [#143] 내 대시보드 가기 경로 수정
  components/DashboardNavbar/DashboardDropdown.tsx
  pages/myboard/index.tsx
Labels: 🛠️ Fix

#146 [#145] 초대하기 오류 해결
  components/DashboardNavbar/DashboardNavbar.tsx
  components/Table/InviteDetailsTable.tsx
  hooks/usePagination.ts
  pages/[dashboardid]/edit.tsx
Labels: 🛠️ Fix

#147 [#118] 구글 로그인 구현 (추가구현)
  .gitignore
  components/GoogleLogin/GoogleLogin.tsx
  constants/SignValidate.ts
  hooks/useAuth.ts
  package-lock.json
  package.json
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: ♻️ Refactor, 📂 Create, 🟢 Feat

#148 [#80] 대시보드 페이지 추가사항 구현/ CSS 등 기타 수정
  components/Chip/ContentChip.tsx
  components/Columns/Card.tsx
  components/Columns/Column.tsx
  components/Columns/Columns.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/Modal/ModalContent/EditToDo.tsx
  components/common/Button/TwinButton.tsx
  hooks/DropDown/useManager.ts
  pages/dashboard/[dashboardid].tsx
Labels: ♻️ Refactor, 🎨 Design, 🛠️ Fix, 🟢 Feat

#152 [#151] MetaData 설정
  constants/Metadata.ts
  pages/_document.tsx
Labels: 📂 Create, 🟢 Feat

#155 [#153] README.md 추가
  README.md
Labels: 📝 Docs, 📂 Create

#157 [#154] Jawstify로 이름 변경
  components/Landing/Hero.tsx
  components/Landing/Nav.tsx
  components/Sidebar/Sidebar.tsx
  components/Table/MembersTable.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/icons/Codeit.svg
  public/assets/icons/LogoSidebar.svg
  public/assets/icons/LogoSidebarTitle.svg
  public/assets/icons/logoImage.svg
  public/assets/icons/logoText.svg
  public/assets/icons/mainPurpleLogo.svg
  public/assets/images/landing1.png
  public/assets/images/landing2.png
  public/assets/images/title.png
  public/assets/images/transJaws.png
Labels: ♻️ Refactor, 📂 Create

#160 [#158] 사용하지 않는 페이지 컴포넌트들 삭제
  pages/boards/index.tsx
  pages/dashboard/index.tsx
  pages/test/index.tsx
Labels: ❌ Remove

#159 [#156] 나의 대시보드 페이지 초대 목록 검색 기능 수정 및 변수명 변경 및 상수 적용
  apis/api.ts
  components/Columns/Card.tsx
  components/Columns/Column.tsx
  components/DashboardNavbar/DashboardNavbar.tsx
  components/DashboardNavbar/Profile.tsx
  components/GoogleLogin/GoogleLogin.tsx
  components/Input/ModalInputContainer/BasicInput.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/Menu.tsx
  components/ModalCard/ModalCard.tsx
  components/MyDashboard/MyDashBoardButtonBox.tsx
  components/Sidebar/Dashboard.tsx
  components/Sidebar/Sidebar.tsx
  components/Table/InviteDashBoard.tsx
  hooks/UseSidebarDashboard.ts
  hooks/useComment.ts
  hooks/useInviteDashBoard.ts
  hooks/useMyDashboard.ts
  hooks/useMyDashboardButtonBox.ts
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  pages/signup/index.tsx
Labels: 🛠️ Fix

#163 [#126] 인풋 글자 색상 수정
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/Table/InviteDashBoard.tsx
Labels: 🎨 Style

#167 [#166] 카드 삭제시, 뒤로가는 버그 수정
  components/ModalCard/Menu.tsx
  hooks/useComment.ts
Labels: 🛠️ Fix

#169 [#168] 댓글 달리면 카드 사라지는 버그 수정
  components/Columns/Column.tsx
Labels: 🛠️ Fix

#175 [#172] React-Helmet Title 추가, Css 및 기능 최종 수정
  components/Columns/Card.tsx
  components/DashboardNavbar/DarkModeToggleButton.tsx
  components/DashboardNavbar/DashboardDropdown.tsx
  components/DashboardNavbar/DashboardNavbar.tsx
  components/DashboardNavbar/Profile.tsx
  components/Landing/Card.tsx
  components/Landing/Hero.tsx
  components/Sidebar/Sidebar.tsx
  package-lock.json
  package.json
  pages/404/index.tsx
  pages/[dashboardid]/edit.tsx
  pages/dashboard/[dashboardid].tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
Labels: 📝 Docs, 🎨 Design, 🛠️ Fix, 🟢 Feat

#174 [#173] 대시보드 페이지 가로 스크롤바 디자인, 모바일일때 카드 컴포넌트 높이 조절
  components/Columns/Card.tsx
  components/Columns/Column.tsx
  components/Columns/Columns.tsx
  components/Input/ModalInputContainer/BasicInput.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/ModalCard/ModalCard.tsx
  components/Sidebar/Dashboard.tsx
  package-lock.json
  package.json
  pages/dashboard/[dashboardid].tsx
Labels: 🎨 Design

#191 [#190] Tanstack query 라이브러리 설치
  package-lock.json
  package.json
Labels: ⚙️ Chore

#193 [#192] Tanstack Query 초기 설정
  pages/_app.tsx
Labels: 🟢 Feat

#184 [#182] 커스텀 훅 분리
  components/AddImageButton/AddImageButton.tsx
  components/Chip/ColorChip.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/MyPage/PasswordManagerBox.tsx
  components/MyPage/ProfileBox.tsx
  constants/ColorEllipse.ts
  hooks/Chip/useColorChip.ts
  hooks/DropDown/useDropDown.ts
  hooks/DropDown/useDropDownMenu.ts
  hooks/DropDown/useManager.ts
  hooks/ModalCard/useModalCard.ts
  hooks/MyPage/usePasswordManagerBox.ts
  hooks/MyPage/useProfileBox.ts
  hooks/useAddImageButton.ts
Labels: ♻️ Refactor, 📂 Create

#188 [#187] 커스텀 훅 분리
  components/Columns/Column.tsx
  components/Columns/Columns.tsx
  components/DashboardNavbar/DarkModeToggleButton.tsx
  components/DashboardNavbar/Members.tsx
  components/DashboardNavbar/Profile.tsx
  components/Edit/DashboardEdit.tsx
  components/GoogleLogin/GoogleLogin.tsx
  components/Input/ModalInputContainer/TagInput.tsx
  components/Landing/Nav.tsx
  components/Modal/ModalContent/CreateToDo.tsx
  components/Modal/ModalContent/EditToDo.tsx
  components/ModalCard/Comment.tsx
  components/ModalCard/Menu.tsx
  components/MyDashboard/MyDashBoardButtonBox.tsx
  components/Sidebar/Dashboard.tsx
  components/Table/InviteDashBoard.tsx
  components/Table/InviteDetailsTable.tsx
  components/Table/MembersTable.tsx
  hooks/Auth/useAuth.ts
  hooks/Auth/useRedirectByLogin.ts
  hooks/Common/useDeviceType.ts
  hooks/Common/usePagination.ts
  hooks/Common/useRefresh.ts
  hooks/Common/useTagInput.ts
  hooks/Common/useTheme.ts
  hooks/Dashboard/UseSidebarDashboard.ts
  hooks/Dashboard/useColumn.ts
  hooks/Dashboard/useDashboard.ts
  hooks/Dashboard/useInviteDashBoard.ts
  hooks/Dashboard/useMyDashboard.ts
  hooks/Dashboard/useMyDashboardButtonBox.ts
  hooks/Dashboard/useRedirectByDashboardId.ts
  hooks/ModalCard/useModalCard.ts
  hooks/Modals/useCreateToDo.ts
  hooks/Modals/useEditTodo.ts
  hooks/global/useUser.ts
  hooks/useComment.ts
  pages/[dashboardid]/edit.tsx
  pages/dashboard/[dashboardid].tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
Labels: ♻️ Refactor, 📂 Create

#196 [#195] Google Analytics 연결
  lib/gtag.js
  pages/_app.tsx
  tsconfig.json
Labels: 📂 Create, ⚙️ Chore, 🟢 Feat

#200 [#199] React-Query 리팩토링 / react-hot-toast
  apis/api.ts
  components/ModalCard/Comment.tsx
  components/ModalCard/Manager.tsx
  components/ModalCard/ModalCard.tsx
  components/ModalDropDown/DropDown.tsx
  components/ModalDropDown/DropDownMenu.tsx
  components/MyPage/ProfileBox.tsx
  hooks/DropDown/useDropDown.ts
  hooks/DropDown/useDropDownMenu.ts
  hooks/ModalCard/useModalCard.ts
  hooks/Modals/useEditTodo.ts
  hooks/MyPage/usePasswordManagerBox.ts
  hooks/MyPage/useProfileBox.ts
  hooks/useComment.ts
  package-lock.json
  package.json
  pages/_app.tsx
  types/api.ts
Labels: ♻️ Refactor, ⚙️ Chore

#202 [#185] 다크모드 색상 정리
  styles/palettes.ts
  styles/theme.ts
Labels: ♻️ Refactor, 🎨 Design

#206 [#205] 폴더 이름 변경으로 인한 오류 / 댓글 수정하기 오류
  apis/queries/cards.ts
  apis/queries/columns.ts
  components/ModalCard/Comment.tsx
  components/Table/InviteDetailsTable.tsx
  components/Table/MembersTable.tsx
  hooks/Common/usePagination.ts
  hooks/Dashboard/useDashboard.ts
  hooks/DashboardNavbar/useDashboardNavbar.ts
  hooks/Edit/useDashboardEdit.ts
  hooks/Edit/useInviteDetailsTable.ts
  hooks/ModalCard/useModalCard.ts
  hooks/useComment.ts
  pages/[dashboardid]/edit.tsx
Labels: ♻️ Refactor, 🛠️ Fix

#207 [#197] Login, Signup React-Query 적용
  apis/queries/auth.ts
  apis/queries/cards.ts
  apis/queries/columns.ts
  apis/queries/dashboard.ts
  apis/queries/users.ts
  components/GoogleLogin/GoogleLogin.tsx
  hooks/Auth/useAuth.ts
  hooks/Common/usePagination.ts
  hooks/DropDown/useDropDown.ts
  hooks/DropDown/useDropDownMenu.ts
  hooks/ModalCard/useModalCard.ts
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: ♻️ Refactor
