Repository CodeJaws/Jawstify, pull requests merged in 2024-03, with the labels that each got.

#213 [#212] mydashboard API 오류 수정
  apis/queries/dashboard.ts
  apis/queries/members.ts
  hooks/Common/usePagination.ts
  hooks/Dashboard/useMyDashboard.ts
  pages/_app.tsx
  pages/mydashboard/index.tsx
Labels: 🛠️ Fix

#215 [#214] 페이지네이션 버튼 이미지 오류 수정
  components/MyDashboard/MyDashBoardButtonBox.tsx
  components/common/Button/LoginButton.tsx
  components/common/Button/PaginationButton.tsx
Labels: 🛠️ Fix

#217 [#216] alert -> toast 전환
  apis/queries/auth.ts
  apis/queries/cards.ts
  apis/queries/columns.ts
  apis/queries/dashboard.ts
  apis/queries/users.ts
  components/GoogleLogin/GoogleLogin.tsx
  components/Modal/ModalContent/CreateDashboard.tsx
  hooks/Auth/useAuth.ts
  hooks/Auth/useRedirectByLogin.ts
  hooks/Dashboard/useDashboard.ts
  hooks/Dashboard/useInviteDashBoard.ts
  hooks/Dashboard/useRedirectByDashboardId.ts
  hooks/DashboardNavbar/useDashboardNavbar.ts
  hooks/DashboardNavbar/useProfile.ts
  hooks/DropDown/useDropDown.ts
  hooks/DropDown/useDropDownMenu.ts
  hooks/Edit/useDashboardEdit.ts
  hooks/Edit/useInviteDetailsTable.ts
  hooks/ModalCard/useModalCard.ts
  hooks/Modals/useCreateToDo.ts
  hooks/Modals/useEditTodo.ts
  hooks/useComment.ts
  hooks/useDashboard.ts
  pages/signup/index.tsx
  types/apiType.ts
Labels: ♻️ Refactor

#219 [#218] accessToken 저장 방식 localStorage -> cookie로 변경
  apis/axios.ts
  apis/queries/auth.ts
  apis/queries/cards.ts
  apis/queries/columns.ts
  apis/queries/dashboard.ts
  apis/queries/members.ts
  apis/queries/users.ts
  components/DashboardNavbar/DashboardDropdown.tsx
  components/GoogleLogin/GoogleLogin.tsx
  constants/QueryKey.ts
  hooks/Auth/useAuth.ts
  hooks/Auth/useRedirectByLogin.ts
  hooks/Modals/useCreateToDo.ts
  hooks/Modals/useEditTodo.ts
  hooks/useDashboard.ts
  package-lock.json
  package.json
  pages/_app.tsx
Labels: ♻️ Refactor, ⚙️ Chore
